config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#login"

  #Categories  
  get '/categories', to: 'categories#index', as: 'categories_index'

  #New Create Pair
  get '/categories/new', to: 'categories#new', as: 'categories_new'
  post '/categories/create', to: 'categories#create', as: 'categories_create'

  #Edit Update Pair
  get '/categories/:category_id/edit', to: 'categories#edit', as: 'categories_edit'
  patch '/categories/:category_id', to: 'categories#update', as: 'categories_update'

  #Delete
  delete '/categories/:category_id/delete', to: 'categories#delete', as: 'categories_delete'


  #Task
  get '/categories/:category_id/tasks', to: 'task#index', as: 'categories_tasks_index'

  get '/categories/:category_id/tasks/new', to: 'task#new', as: 'categories_tasks_new'
  post '/categories/:category_id/tasks/create', to: 'task#create', as: 'categories_tasks_create'
  
  get '/categories/:category_id/tasks/:id/edit', to: 'task#edit', as: 'categories_tasks_edit'
  patch '/categories/:category_id/tasks/:id', to: 'task#update', as: 'categories_tasks_update'

  delete '/categories/:category_id/tasks/:id/delete', to: 'task#delete', as: 'categories_tasks_delete'


  #Sessions
  get '/login', to: 'sessions#login', as: 'sessions_login'
  post 'login/create', to: 'sessions#login_create', as: 'sessions_login_create'
  get '/signup', to: 'sessions#signup', as: 'sessions_signup'
  post '/signup/create', to: 'sessions#signup_create', as: 'sessions_signup_create'
  get '/logout', to: 'sessions#logout', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :user_id, presence:true, numericality: { only_integer: true }
    has_many :tasks, dependent: :destroy
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord 
  attr_accessor :confirm_password
  validates :username, presence: true, uniqueness: true  
  has_secure_password
  has_many :categories
  has_many :tasks, through: :categories


  def self.authenticate(username, password)
    user = find_by(username: username)
    if user && BCrypt::Password.new(user.password_digest) == password
      user
    else
      nil
    end
  end  

  def owned_categories
    categories.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :load_categories

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authenticate_user!
    redirect_to sessions_login_path, alert: "Please log in to access this page." unless current_user
    end
    helper_method :current_user

  
    
    def load_categories
        # @categories_all = Category.all
        # @categories_new = Category.new
        # @categories_find = Category.find(params[:category_id]) if params[:category_id].present?
        
        @categories_tasks = Category.find(params[:category_id]).tasks if params[:category_id].present?
        @categories_task_find = Category.find(params[:category_id]).tasks.find(params[:id]) if (params[:category_id].present? && params[:id].present?)        
        
        @categories_tasks_new = Category.find(params[:category_id]).tasks.new if params[:category_id].present?

        if current_user.present?
            @categories_all = current_user.owned_categories
          else
            # handle the case where current_user is nil
            # for example, you could redirect to a login page
          end
        
        @categories_new = Category.new
        @categories_find = Category.find(params[:category_id]) if params[:category_id].present?
                
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index        
    end
 
    def new
    end

    def create
        @category = current_user.owned_categories.build(category_params)
        if @category.save
            redirect_to categories_index_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit        
    end

    def update                 
        if @categories_find.update(category_params)
            redirect_to categories_index_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def delete
        @categories_find.destroy
        redirect_to categories_index_path
        
    end

    def category_params
        params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login
    end

    def login_create
      if params[:login].present? && params[:login][:username].present? && params[:login][:password_digest].present?
        user = User.authenticate(params[:login][:username], params[:login][:password_digest])
        if user
          session[:user_id] = user.id
          redirect_to categories_index_path, notice: 'Successfully logged in!'
          @message = "Successfully logged in as #{user.username}"
        else
          flash.now[:alert] = 'Invalid username or password'
          @message = 'Invalid username or password'
        end
      else
        @message = 'Please enter your username and password'
      end
    end

    def logout
        session[:user_id] = nil
        redirect_to sessions_login_path, notice: "Logged out!"
    end

    def signup        
    end

    def signup_create
        @user = User.new(signup_params) 
        if @user.save
          # user successfully created
        else
          flash.now[:alert] = @user.errors.full_messages.join(", ")
          render :signup
        end
      end

    def signup_params        
            signup_params = params.require(:signup).permit(:username, :password, :confirm_password)
    end

    def login_params        
            login_params = params.require(:login).permit(:username, :password_digest)        
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

    def index        
    end

    def new        
    end

    def create
        @categories_tasks_create = Category.find(params[:category_id]).tasks.new(task_params)

        if @categories_tasks_create.save
            redirect_to categories_tasks_index_path
        else
            render :new, status: :unprocessable_entity
        end        
    end

    def edit               
    end

    def update
        if @categories_task_find.update(task_params)
            redirect_to categories_tasks_index_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def delete
        @categories_task_find.destroy
        redirect_to categories_tasks_index_path
    end
        
    def task_params
        params.require(:task).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
<h3 style="width: 200px;padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;">Edit Category</h3>

<%= form_with scope: @categories_find, url: categories_update_path(@categories_find), method: :patch, html: { autocomplete: 'off' } do |form| %>


<% if @categories_find.errors.any? %>
  <ul>
    <% @categories_find.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

    <div>
        <%= form.label :name %><br/>
        <%= form.text_field :name %>
    </div>

    <!-- <div>
        <%= form.label :user_id %><br/>
        <%= form.text_field :user_id %>
     </div> -->

  <div>
    <%= form.submit "Save Changes" %>
  </div>
<% end %>

app/views/categories/_index.html.erb
<h3 style="width: 200px; padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;">Category</h3>
<table style="width: 220px;">
    <thead>
        <tr>
            <!-- <th>ID</th> -->
            <th></th>
            <!-- <th>User_ID</th> -->
        </tr>
    </thead>
    <tbody>
        <% @categories_all.each do |category| %>
        <tr>        
            <!-- <td><%= category.id  %></td> -->
            <td style="color:black;width:100px;"><%= link_to category.name, categories_tasks_index_path(category.id) %></td>
            <!-- <td><%= category.user_id %></td> -->
            <td style="padding-left:20px;width:50px"><%= link_to 'Edit', categories_edit_path(category), method: :edit %></td>            
            <td style="width:50px;"><%= button_to 'Delete', categories_delete_path(category.id), method: :delete%></td>
            <!-- <td><%= category.id.inspect %></td> -->
        </tr>
        <% end %>
    </tbody>
</table>
<p style="text-align:center; margin: 20px 0px; width: 200px;"><%= link_to("Add New Category", categories_new_path) %></p>

app/views/categories/_new.html.erb
<h3 style="width: 200px;padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;">New Category</h3>

<%= form_with scope: :category, url: categories_create_path, html:{autocomplete: 'off'} do |form| %>

  <% if @categories_new.errors.any? %>
  <ul>
    <% @categories_new.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


  <%= form.label :name %><br/>
  <%= form.text_field :name %><br/>

  <!-- <%= form.label :user_id %><br/>
  <%= form.text_field :user_id %><br/> -->

  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render "index"%>
<%= render "edit" %>

app/views/categories/index.html.erb
<%= render "index" %>

app/views/categories/new.html.erb
<%= render "index"%>
<%= render "new" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
  </head>
  <body>  
  <%= image_tag asset_path("Journal Logo.png"), size: "200x80" %>
    <div style="margin: 20px">
    
    <% if current_user %>
    <p style = "margin: 0px; color: black; display:flex; justify-content:space-between; width: 220px;">Welcome, <%= current_user.username.upcase %>
    <%= link_to "Logout", logout_path, method: :delete %>
    </p>
    <% end %>
  
    <%= yield %>

  </body>
</html>

app/views/task/_edit.html.erb
<div style="display:flex; flex-direction:column; margin-left: 70px">
<h3 style="width: 200px;padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;">Edit Task</h3>

<%= form_with scope: @categories_task_find, url: categories_tasks_update_path, method: :patch, html: { autocomplete: 'off' } do |form| %>
<% if @categories_task_find.errors.any? %>
  <ul>
    <% @categories_task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

    <div>
        <%= form.label :name %><br/>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :description %><br/>
        <%= form.text_field :description %>
     </div>

  <div>
    <%= form.submit "Save Changes" %>
  </div>
<% end %>
</div>

app/views/task/_index.html.erb
<div style="display:flex;">

<div style="margin:0px; padding:0px;">
<%= render partial: 'categories/index' %>
</div>

<div style="width: 500px; margin-left:5vw; padding:0px;">
<h3 style="width: 500px;padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;"><%= @categories_find.name  %>'s Task</h3>
  <table>
    <thead>
      <tr>
        <th style="width:20%; padding:10px;">Name</th>
        <th style="width:50%; padding:10px;">Description</th>
        <th style="width:30%; padding:10px;">Date Created</th>
      </tr>
    </thead>
    
    <tbody>        
      <% @categories_tasks.each do |task| %>        
        <tr>          
          <td style="text-align:center"><%= task.name %></td>
          <td style="text-align:center"><%= task.description %></td>
          <td style="text-align:center"><%= task.created_at.strftime('%m-%d-%Y') %></td>
          <td><%= link_to "Edit",categories_tasks_edit_path(category_id: task.category_id, id: task.id), method: :edit %></td>
          <td><%= button_to "Delete",categories_tasks_delete_path(category_id: task.category_id, id: task.id), method: :delete %></td>
        </tr>      
      <% end %>              
    </tbody>    
  </table>
  <p style="text-align:center;margin: 20px 0px;"><%= link_to 'New Task', categories_tasks_new_path%></p>
</div>

app/views/task/_new.html.erb
<div style="display:flex; flex-direction:column; padding: 0 50px; margin-left: 20px;">
<h3 style="width: 200px;padding: 10px;margin: 0px;background-color: #036642; color: white; font-family: arial;">New Task Adding</h3>
<%= form_with scope: :task, url: categories_tasks_create_path, html:{autocomplete: 'off'} do |form| %>

    <% if @categories_tasks_new.errors.any? %>
    <ul>
      <% @categories_tasks_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  
  
    <%= form.label :name %><br/>
    <%= form.text_field :name %><br/>
  
    <%= form.label :description %><br/>
    <%= form.text_field :description %><br/>
  
    <%= form.submit %>
  <% end %>
</div>

app/views/task/edit.html.erb
<%= render "index" %>
<%= render "edit" %>

app/views/task/index.html.erb
<%= render "index" %>

app/views/task/new.html.erb
<%= render "index" %>
<%= render "new" %>